"""Update duration column to float

Revision ID: b4a360343afd
Revises:
Create Date: 2024-12-04 21:44:10.758656

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "777435584774"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "election",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finishes_at", sa.DateTime(), nullable=False),
        sa.Column("winner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_election_finishes_at"), "election", ["finishes_at"], unique=False
    )
    op.create_table(
        "movie",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("imdb", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("premiere_date", sa.DateTime(), nullable=True),
        sa.Column("rating", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movie_title"), "movie", ["title"], unique=False)
    op.create_table(
        "electionmovielink",
        sa.Column("election_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("movie_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["election.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
        ),
        sa.PrimaryKeyConstraint("election_id", "movie_id"),
    )
    op.create_table(
        "vote",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("election_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("movie_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["election.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vote")
    op.drop_table("electionmovielink")
    op.drop_index(op.f("ix_movie_title"), table_name="movie")
    op.drop_table("movie")
    op.drop_index(op.f("ix_election_finishes_at"), table_name="election")
    op.drop_table("election")
    # ### end Alembic commands ###
